### ISSUE TITLE
File jfairy_ita.yml was not found on classpath

### ISSUE THREAD

**Issue by realulim** [Devskiller/jfairy#117]
I included JFairy in my gradle build via

`compile('io.codearte.jfairy:jfairy:0.5.9')`

and generated a Person. The following stack trace appears at runtime:

`Caused by: java.lang.IllegalArgumentException: File jfairy_ita.yml was not found on classpath
	at io.codearte.jfairy.data.MapBasedDataMaster.readResources(MapBasedDataMaster.java:100) ~[jfairy-0.5.9.jar:0.5.9]
	at io.codearte.jfairy.Bootstrap.fillDefaultDataMaster(Bootstrap.java:59) ~[jfairy-0.5.9.jar:0.5.9]
	at io.codearte.jfairy.Bootstrap.access$100(Bootstrap.java:38) ~[jfairy-0.5.9.jar:0.5.9]
	at io.codearte.jfairy.Bootstrap$Builder.build(Bootstrap.java:225) ~[jfairy-0.5.9.jar:0.5.9]
	at io.codearte.jfairy.Bootstrap.create(Bootstrap.java:93) ~[jfairy-0.5.9.jar:0.5.9]
	at io.codearte.jfairy.Fairy.create(Fairy.java:52) ~[jfairy-0.5.9.jar:0.5.9]`

**Comment by realulim** [comment]
Ok, so the locale needs to be two letters (it instead of ita). Perhaps the docs should mention which locales are supported (linking to https://github.com/Devskiller/jfairy/tree/master/src/main/resources should do the trick).
